version: '3'
services:
  django_todo_app:
    container_name: django_todo_app
    build:
      context: ./
      dockerfile: docker/Dockerfile
    volumes:
      - ./todo_project:/var/www/todo_project
    env_file:
      - .env
    working_dir: /var/www/todo_project
    command: /entrypoint.sh
    ports:
      - '8990:8000'
    networks:
      - todoapp-network
    depends_on:
      - todo_db

  todo_db:
    platform: linux/x86_64
    image: mysql:8.1
    container_name: todo_db
    restart: unless-stopped
    tty: true
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    ports:
      - "3307:3306"
    volumes:
      - ./db-data/local:/var/lib/mysql
    networks:
      - todoapp-network
    healthcheck:
      test: "exit 0"

networks:
  todoapp-network:
    driver: bridge
    ipam:
      config:
        - subnet: 172.16.220.0/24